name: Terraform GKE Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Code
        uses: actions/checkout@v2

      - name: Configure GCP credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: career-project # Replace with your GCP project ID
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9 # Replace with desired Terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Format Terraform Code
        run: terraform fmt -check

      - name: Plan Terraform changes
        run: terraform plan -detailed-exitcode

      - name: Apply Terraform changes
        run: terraform apply -auto-approve

  destroy:
    needs: deploy
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: <version> # Replace with desired Terraform version

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: <project-id> # Replace with your GCP project ID
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Initialize Terraform
        run: terraform init

      - name: Destroy Terraform infrastructure
        run: terraform destroy -auto-approve
